/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Vehicle vehicleA = new Vehicle("Vehicle A", "Benz");
        vehicleA.SpeedUp(50);

        Vehicle vehicleB = new Vehicle("Vehicle B", "Toyota");
        vehicleB.SpeedUp(40);

        Car car = new Car("Car A", "Goodbye");
        car.SpeedUp(180);
        car.SpeedUp(201);

        Bus bus = new Bus ("Bus A","OOCL");
        bus.SpeedUp(70);
        bus.SpeedUp(100);

        Driver venice = new Driver(vehicleA,"Venice");
        venice.SpeedUp(120);

        Driver amy = new Driver(bus,"Amy");
        amy.SpeedUp(230);
    }
}



class Driver{
   String name;
   Vehicle vehicle;

    public Driver (Vehicle vehicle, String name){
        this.vehicle = vehicle;
        this.name = name;
    }

    public void SpeedUp(int speed){
        System.out.println("I am driver, my name is " + this.name);
        this.vehicle.SpeedUp(speed);
    }
}

