/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Vehicle vehicleA = new Vehicle("Vehicle A", "Benz");
        vehicleA.SpeedUp(50);

        Vehicle vehicleB = new Vehicle("Vehicle B", "Toyota");
        vehicleB.SpeedUp(40);

        Car car = new Car("Car A", "Goodbye");
        car.SpeedUp(180);
        car.SpeedUp(201);
    }
}


class Vehicle {

    private String name;
    private String brand;

    public Vehicle(String name, String brand) {
        this.name = name;
        this.brand = brand;


    }

    public void SpeedUp(int speed) {
        System.out.println("Name: " + this.name + " Brand: " + this.brand + " Speed: " + speed);
    }


}

class Car extends Vehicle{
    public Car(String name, String brand){
        super(name, brand);
    }
    @Override
    public void SpeedUp(int speed){
        if (speed >= 190){
            super.SpeedUp(speed);
        } else{
            System.out.println("Fail to speedup!");
        }
    }
}

