/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Vehicle vehicleA = new Vehicle("Car A", "Benz");
        vehicleA.SpeedUp(50);
        Vehicle vehicleB = new Vehicle("Car B", "Toyota");
        vehicleB.SpeedUp(40);
    }
}


class Vehicle {

    private String name;
    private String brand;

    public Vehicle(String name, String brand) {
        this.name = name;
        this.brand = brand;


    }

    public void SpeedUp(int speed) {
        System.out.println("Name: " + this.name + " Brand: " + this.brand + " Speed: " + speed);
    }


}

